[2022-01-06 17:47:49,823] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: emailoperator_demo.send_email scheduled__2022-01-05T00:00:00+00:00 [queued]>
[2022-01-06 17:47:49,832] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: emailoperator_demo.send_email scheduled__2022-01-05T00:00:00+00:00 [queued]>
[2022-01-06 17:47:49,832] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-06 17:47:49,832] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-01-06 17:47:49,832] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-06 17:47:49,842] {taskinstance.py:1259} INFO - Executing <Task(EmailOperator): send_email> on 2022-01-05 00:00:00+00:00
[2022-01-06 17:47:49,845] {standard_task_runner.py:52} INFO - Started process 69008 to run task
[2022-01-06 17:47:49,851] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'emailoperator_demo', 'send_email', 'scheduled__2022-01-05T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/email_operator_demo.py', '--cfg-path', '/var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T/tmppznh93m1', '--error-file', '/var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T/tmpzsxfuihl']
[2022-01-06 17:47:49,853] {standard_task_runner.py:77} INFO - Job 99: Subtask send_email
[2022-01-06 17:47:49,896] {logging_mixin.py:109} INFO - Running <TaskInstance: emailoperator_demo.send_email scheduled__2022-01-05T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-01-06 17:47:49,938] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nivu2211@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=emailoperator_demo
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2022-01-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-05T00:00:00+00:00
[2022-01-06 17:47:49,949] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py:102 PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2022-01-06 17:47:49,949] {configuration.py:381} WARNING - section/key [smtp/smtp_user] not found in config
[2022-01-06 17:47:49,949] {email.py:208} INFO - Email alerting: attempt 1
[2022-01-06 17:47:49,951] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/email.py", line 88, in execute
    conn_id=self.conn_id,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 66, in send_email
    **kwargs,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 102, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 210, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 244, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
[2022-01-06 17:47:49,964] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=emailoperator_demo, task_id=send_email, execution_date=20220105T000000, start_date=20220106T121749, end_date=20220106T121749
[2022-01-06 17:47:49,972] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-01-06 17:47:49,973] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-01-06 17:47:49,975] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-01-06 17:47:49,976] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-01-06 17:47:49,977] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-01-06 17:47:49,978] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-01-06 17:47:49,979] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-01-06 17:47:49,980] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-01-06 17:47:49,981] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-01-06 17:47:49,982] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-01-06 17:47:49,983] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-01-06 17:47:49,984] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-01-06 17:47:49,992] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py:102 PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2022-01-06 17:47:49,993] {configuration.py:381} WARNING - section/key [smtp/smtp_user] not found in config
[2022-01-06 17:47:49,993] {email.py:208} INFO - Email alerting: attempt 1
[2022-01-06 17:47:49,998] {configuration.py:381} WARNING - section/key [smtp/smtp_user] not found in config
[2022-01-06 17:47:49,998] {email.py:208} INFO - Email alerting: attempt 1
[2022-01-06 17:47:49,999] {taskinstance.py:1751} ERROR - Failed to send email to: ['nivu2211@gmail.com']
Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/email.py", line 88, in execute
    conn_id=self.conn_id,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 66, in send_email
    **kwargs,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 102, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 210, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 244, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2093, in email_alert
    send_email(self.task.email, subject, html_content)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 66, in send_email
    **kwargs,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 102, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 210, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 244, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1749, in handle_failure
    self.email_alert(error)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2095, in email_alert
    send_email(self.task.email, subject, html_content_err)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 66, in send_email
    **kwargs,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 102, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 210, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 244, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
[2022-01-06 17:47:50,009] {standard_task_runner.py:92} ERROR - Failed to execute job 99 for task send_email
Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/email.py", line 88, in execute
    conn_id=self.conn_id,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 66, in send_email
    **kwargs,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 102, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 210, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/email.py", line 244, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
[2022-01-06 17:47:50,038] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-06 17:47:50,060] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
