[2022-01-07 16:00:14,496] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: booking_ingestion.load_data manual__2022-01-07T10:30:06.180564+00:00 [queued]>
[2022-01-07 16:00:14,504] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: booking_ingestion.load_data manual__2022-01-07T10:30:06.180564+00:00 [queued]>
[2022-01-07 16:00:14,504] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-07 16:00:14,504] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-07 16:00:14,504] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-07 16:00:14,513] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): load_data> on 2022-01-07 10:30:06.180564+00:00
[2022-01-07 16:00:14,515] {standard_task_runner.py:52} INFO - Started process 91592 to run task
[2022-01-07 16:00:14,521] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'booking_ingestion', 'load_data', 'manual__2022-01-07T10:30:06.180564+00:00', '--job-id', '340', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T/tmpdcxky74f', '--error-file', '/var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T/tmpyyenc_1i']
[2022-01-07 16:00:14,523] {standard_task_runner.py:77} INFO - Job 340: Subtask load_data
[2022-01-07 16:00:14,567] {logging_mixin.py:109} INFO - Running <TaskInstance: booking_ingestion.load_data manual__2022-01-07T10:30:06.180564+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-01-07 16:00:14,598] {logging_mixin.py:109} WARNING - /Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-01-07 16:00:14,609] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nivedita
AIRFLOW_CTX_DAG_ID=booking_ingestion
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2022-01-07T10:30:06.180564+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-07T10:30:06.180564+00:00
[2022-01-07 16:00:14,610] {logging_mixin.py:109} INFO - Loading data for date: 2022-01-07 10
[2022-01-07 16:00:14,617] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/admin/Desktop/airflow-tutorial/dags/main.py", line 75, in load_data
    conn = SQLiteDatabase.connect("/Users/admin/Desktop/airflow-tutorial/airflow.db")
AttributeError: type object 'SQLiteDatabase' has no attribute 'connect'
[2022-01-07 16:00:14,625] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=booking_ingestion, task_id=load_data, execution_date=20220107T103006, start_date=20220107T103014, end_date=20220107T103014
[2022-01-07 16:00:14,635] {standard_task_runner.py:92} ERROR - Failed to execute job 340 for task load_data
Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/admin/Desktop/airflow-tutorial/dags/main.py", line 75, in load_data
    conn = SQLiteDatabase.connect("/Users/admin/Desktop/airflow-tutorial/airflow.db")
AttributeError: type object 'SQLiteDatabase' has no attribute 'connect'
[2022-01-07 16:00:14,668] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-07 16:00:14,688] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
