[2022-01-06 16:23:17,020] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: print_random_number.print_6 scheduled__2021-12-31T00:00:00+00:00 [queued]>
[2022-01-06 16:23:17,027] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: print_random_number.print_6 scheduled__2021-12-31T00:00:00+00:00 [queued]>
[2022-01-06 16:23:17,027] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-06 16:23:17,027] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-01-06 16:23:17,027] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-06 16:23:17,036] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): print_6> on 2021-12-31 00:00:00+00:00
[2022-01-06 16:23:17,038] {standard_task_runner.py:52} INFO - Started process 62726 to run task
[2022-01-06 16:23:17,044] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'print_random_number', 'print_6', 'scheduled__2021-12-31T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/print_random.py', '--cfg-path', '/var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T/tmp0dkhz5ok', '--error-file', '/var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T/tmpz4n4i1xh']
[2022-01-06 16:23:17,046] {standard_task_runner.py:77} INFO - Job 45: Subtask print_6
[2022-01-06 16:23:17,087] {logging_mixin.py:109} INFO - Running <TaskInstance: print_random_number.print_6 scheduled__2021-12-31T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-01-06 16:23:17,122] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=print_random_number
AIRFLOW_CTX_TASK_ID=print_6
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-31T00:00:00+00:00
[2022-01-06 16:23:17,123] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T
[2022-01-06 16:23:17,124] {subprocess.py:74} INFO - Running command: ['bash', '-c', <function print_six at 0x7fa50307bf80>]
[2022-01-06 16:23:17,125] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/bash.py", line 182, in execute
    cwd=self.cwd,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 82, in run_command
    preexec_fn=pre_exec,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not function
[2022-01-06 16:23:17,135] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=print_random_number, task_id=print_6, execution_date=20211231T000000, start_date=20220106T105317, end_date=20220106T105317
[2022-01-06 16:23:17,145] {standard_task_runner.py:92} ERROR - Failed to execute job 45 for task print_6
Traceback (most recent call last):
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/operators/bash.py", line 182, in execute
    cwd=self.cwd,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 82, in run_command
    preexec_fn=pre_exec,
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not function
[2022-01-06 16:23:17,187] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-06 16:23:17,215] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
